import { ProfileWithLinks, Service } from '@/lib/types/database'

export const DEMO_USERNAME = 'kaniel'

export const demoProfile: ProfileWithLinks = {
  id: 'demo-kaniel-001',
  username: 'kaniel',
  display_name: 'Kaniel Tordjman',
  bio: 'Full Stack Developer & AI Builder | Solar Energy Entrepreneur | Building the future with code',
  avatar_url: '/demo/clean-800.png',
  theme: {
    primaryColor: '#38bdf8',
    backgroundColor: '#030712',
    fontFamily: 'Plus Jakarta Sans',
    buttonStyle: 'glass',
  },
  is_premium: true,
  custom_domain: null,
  created_at: '2025-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
  links: [
    {
      id: 'demo-link-1',
      profile_id: 'demo-kaniel-001',
      title: 'Navitas CRM',
      url: 'https://crm.navitas.co.il',
      icon: '☀️',
      position: 0,
      is_active: true,
      click_count: 1247,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-link-2',
      profile_id: 'demo-kaniel-001',
      title: 'AI Course — Your First Assistant',
      url: 'https://kaniel149.github.io/kaniel-course',
      icon: '🎓',
      position: 1,
      is_active: true,
      click_count: 893,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-link-3',
      profile_id: 'demo-kaniel-001',
      title: 'GitHub — Open Source',
      url: 'https://github.com/kaniel149',
      icon: '💻',
      position: 2,
      is_active: true,
      click_count: 654,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-link-4',
      profile_id: 'demo-kaniel-001',
      title: 'Brand Hub — Portfolio',
      url: 'https://kaniel149.github.io',
      icon: '🏠',
      position: 3,
      is_active: true,
      click_count: 432,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-link-5',
      profile_id: 'demo-kaniel-001',
      title: 'AI Readiness Scorecard',
      url: 'https://kaniel149.github.io/kaniel-scorecard',
      icon: '🧮',
      position: 4,
      is_active: true,
      click_count: 318,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-link-6',
      profile_id: 'demo-kaniel-001',
      title: 'Command Center — Life OS',
      url: 'https://kaniel149.github.io/kaniel-command-center',
      icon: '📊',
      position: 5,
      is_active: true,
      click_count: 276,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
  ],
  social_embeds: [
    {
      id: 'demo-social-1',
      profile_id: 'demo-kaniel-001',
      platform: 'linkedin',
      embed_url: 'https://www.linkedin.com/in/kaniel-turdjman-2000a4189/',
      position: 0,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-social-2',
      profile_id: 'demo-kaniel-001',
      platform: 'twitter',
      embed_url: 'https://x.com/kaniel149',
      position: 1,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-social-3',
      profile_id: 'demo-kaniel-001',
      platform: 'instagram',
      embed_url: 'https://instagram.com/kaniel.t',
      position: 2,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-social-4',
      profile_id: 'demo-kaniel-001',
      platform: 'github',
      embed_url: 'https://github.com/kaniel149',
      position: 3,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-social-5',
      profile_id: 'demo-kaniel-001',
      platform: 'youtube',
      embed_url: 'https://youtube.com/@kaniel',
      position: 4,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
  ],
}

export const demoServices: Service[] = [
  {
    id: 'demo-service-1',
    profile_id: 'demo-kaniel-001',
    title: 'AI Integration Consulting',
    description: 'I help businesses integrate AI into their workflows — from chatbots to automated pipelines. Let\'s find the right AI strategy for your team.',
    category: 'consulting',
    pricing: 'hourly',
    price_amount: 150,
    price_currency: 'USD',
    action_type: 'book_meeting',
    action_config: {},
    position: 0,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'demo-service-2',
    profile_id: 'demo-kaniel-001',
    title: 'Full Stack Development',
    description: 'Custom web applications with React, Next.js, and Node.js. From MVP to production-ready systems.',
    category: 'freelance',
    pricing: 'custom',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'request_quote',
    action_config: {},
    position: 1,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'demo-service-3',
    profile_id: 'demo-kaniel-001',
    title: 'AI Readiness Workshop',
    description: 'A hands-on workshop for teams looking to understand and adopt AI tools. Covers prompt engineering, automation, and best practices.',
    category: 'education',
    pricing: 'fixed',
    price_amount: 500,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 2,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
]
