import { ProfileWithLinks, Service } from '@/lib/types/database'

export const DEMO_USERNAME = 'kaniel'

export const demoProfile: ProfileWithLinks = {
  id: 'demo-kaniel-001',
  username: 'kaniel',
  display_name: 'Kaniel Tordjman',
  bio: 'Solar energy entrepreneur & CEO at Navitas | Partner & father of 3 | Building AI agents to automate the boring stuff and free up time for what truly matters',
  avatar_url: '/demo/clean-800.png',
  theme: {
    primaryColor: '#38bdf8',
    backgroundColor: '#030712',
    fontFamily: 'Plus Jakarta Sans',
    buttonStyle: 'glass',
  },
  is_premium: true,
  custom_domain: null,
  created_at: '2025-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
  links: [
    {
      id: 'demo-link-1',
      profile_id: 'demo-kaniel-001',
      title: 'Navitas Solar CRM — AI-Powered Project Management',
      url: '/projects/navitas',
      icon: '☀️',
      position: 0,
      is_active: true,
      click_count: 1247,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-link-2',
      profile_id: 'demo-kaniel-001',
      title: 'Lavi — Smart Distribution & Delivery System',
      url: '/projects/lavi',
      icon: '🦁',
      position: 1,
      is_active: true,
      click_count: 893,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-link-3',
      profile_id: 'demo-kaniel-001',
      title: 'LinkHub — AI-Agent Ready Personal Brand Platform',
      url: '/',
      icon: '🔗',
      position: 2,
      is_active: true,
      click_count: 654,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-link-4',
      profile_id: 'demo-kaniel-001',
      title: 'Kaniel OS — Personal Life Operating System',
      url: '/projects/kaniel-os',
      icon: '🧠',
      position: 3,
      is_active: true,
      click_count: 432,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-link-5',
      profile_id: 'demo-kaniel-001',
      title: 'GitHub — Open Source Projects',
      url: 'https://github.com/kaniel149',
      icon: '💻',
      position: 4,
      is_active: true,
      click_count: 318,
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
  ],
  social_embeds: [
    {
      id: 'demo-social-1',
      profile_id: 'demo-kaniel-001',
      platform: 'linkedin',
      embed_url: 'https://www.linkedin.com/in/kaniel-turdjman-2000a4189/',
      position: 0,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-social-2',
      profile_id: 'demo-kaniel-001',
      platform: 'instagram',
      embed_url: 'https://www.instagram.com/kaniel_tord',
      position: 1,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-social-3',
      profile_id: 'demo-kaniel-001',
      platform: 'twitter',
      embed_url: 'https://x.com/kaniel149',
      position: 2,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-social-4',
      profile_id: 'demo-kaniel-001',
      platform: 'github',
      embed_url: 'https://github.com/kaniel149',
      position: 3,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
    {
      id: 'demo-social-5',
      profile_id: 'demo-kaniel-001',
      platform: 'youtube',
      embed_url: 'https://youtube.com/@kaniel',
      position: 4,
      is_active: true,
      created_at: '2025-01-01T00:00:00Z',
    },
  ],
}

export const demoServices: Service[] = [
  {
    id: 'demo-service-1',
    profile_id: 'demo-kaniel-001',
    title: 'Navitas Solar CRM',
    description: 'Full CRM for managing solar energy projects — from lead to installation. Includes monitoring dashboards (SolarEdge, Huawei, Sungrow), IEC licensing tracker, Nipendo invoice automation, CFO analytics, and real-time WhatsApp alerts. Built with React, TypeScript, and Supabase.',
    category: 'product',
    pricing: 'custom',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 0,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'demo-service-2',
    profile_id: 'demo-kaniel-001',
    title: 'Lavi Distribution System',
    description: 'Mobile-first PWA for managing delivery fleets — driver app with route optimization, loading verification, digital signatures, and return handling. Manager dashboard with real-time tracking, Excel imports, and automated alerts. Built for food distribution with offline-first architecture.',
    category: 'product',
    pricing: 'custom',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 1,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'demo-service-3',
    profile_id: 'demo-kaniel-001',
    title: 'LinkHub — AI-Ready Personal Brand',
    description: 'The link-in-bio platform that AI agents can read and act on. Every profile gets two doors — a beautiful animated page for humans and a structured MCP endpoint for AI agents. Includes services marketplace, agent analytics, API keys, and integration connectors.',
    category: 'product',
    pricing: 'free',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'external_link',
    action_config: {},
    position: 2,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'demo-service-4',
    profile_id: 'demo-kaniel-001',
    title: 'Kaniel OS — Life Operating System',
    description: 'Personal productivity system powered by AI agents — morning briefing podcast (auto-generated daily news via NotebookLM), Whoop health sync, Obsidian knowledge capture, task management, calendar integration, and social intelligence automation. The command center for life.',
    category: 'product',
    pricing: 'contact',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 3,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
]
