import { ProfileWithLinks, Service } from '@/lib/types/database'

export const BAR_USERNAME = 'bar'

export const barProfile: ProfileWithLinks = {
  id: 'demo-bar-001',
  username: 'bar',
  display_name: 'Bar Refaeli',
  bio: '\u{1F457} Supermodel & Entrepreneur | \u{1F1EE}\u{1F1F1} Sports Illustrated Cover | Carolina Lemke Co-Owner | TV Host | Mother of 3',
  avatar_url: '/demo/bar/avatar.jpg',
  theme: {
    primaryColor: '#B76E79',
    backgroundColor: '#050505',
    fontFamily: 'Plus Jakarta Sans',
    buttonStyle: 'glass',
  },
  is_premium: true,
  custom_domain: null,
  onboarding_completed_at: '2024-01-01T00:00:00Z',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
  links: [
    {
      id: 'bar-link-1',
      profile_id: 'demo-bar-001',
      title: '\u{1F453} Carolina Lemke \u2014 Eyewear Collection',
      url: 'https://www.carolinalemke.com',
      icon: '\u{1F453}',
      position: 0,
      is_active: true,
      click_count: 62400,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'bar-link-2',
      profile_id: 'demo-bar-001',
      title: '\u{1F9E5} HOODIES by Bar \u2014 Fashion Brand',
      url: 'https://www.hoodiesbybar.com',
      icon: '\u{1F9E5}',
      position: 1,
      is_active: true,
      click_count: 41700,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'bar-link-3',
      profile_id: 'demo-bar-001',
      title: '\u{1F4FA} X Factor Israel \u2014 Host & Judge',
      url: 'https://www.imdb.com/title/tt3442498/',
      icon: '\u{1F4FA}',
      position: 2,
      is_active: true,
      click_count: 29300,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'bar-link-4',
      profile_id: 'demo-bar-001',
      title: '\u{1F525} Sports Illustrated Swimsuit Feature',
      url: 'https://swimsuit.si.com/model/bar-refaeli',
      icon: '\u{1F525}',
      position: 3,
      is_active: true,
      click_count: 53100,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'bar-link-5',
      profile_id: 'demo-bar-001',
      title: '\u{1F3AC} IMDB \u2014 Full Filmography & TV',
      url: 'https://www.imdb.com/name/nm2111802/',
      icon: '\u{1F3AC}',
      position: 4,
      is_active: true,
      click_count: 18900,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'bar-link-6',
      profile_id: 'demo-bar-001',
      title: '\u2764\uFE0F Under Armour \u2014 Global Campaign',
      url: 'https://www.underarmour.com',
      icon: '\u2764\uFE0F',
      position: 5,
      is_active: true,
      click_count: 14600,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  social_embeds: [
    {
      id: 'bar-social-1',
      profile_id: 'demo-bar-001',
      platform: 'instagram',
      embed_url: 'https://www.instagram.com/barrefaeli/',
      position: 0,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'bar-social-2',
      profile_id: 'demo-bar-001',
      platform: 'twitter',
      embed_url: 'https://x.com/BarRefaeli',
      position: 1,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'bar-social-3',
      profile_id: 'demo-bar-001',
      platform: 'youtube',
      embed_url: 'https://www.youtube.com/results?search_query=bar+refaeli',
      position: 2,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
  ],
}

export const barServices: Service[] = [
  {
    id: 'bar-service-1',
    profile_id: 'demo-bar-001',
    title: 'Carolina Lemke \u2014 Eyewear Collection',
    description: 'Co-owner of Carolina Lemke Berlin, a global eyewear brand offering designer sunglasses and optical frames. Shop the latest collections inspired by fashion-forward design and Tel Aviv style.',
    category: 'product',
    pricing: 'fixed',
    price_amount: 89,
    price_currency: 'USD',
    action_type: 'external_link',
    action_config: { url: 'https://www.carolinalemke.com' },
    position: 0,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'bar-service-2',
    profile_id: 'demo-bar-001',
    title: 'Brand Ambassadorship & Campaigns',
    description: 'Partner with one of the world\'s most recognized supermodels for global brand campaigns, product launches, and ambassador programs. Reach audiences across fashion, beauty, lifestyle, and luxury markets worldwide.',
    category: 'consulting',
    pricing: 'custom',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'bar-service-3',
    profile_id: 'demo-bar-001',
    title: 'Modeling & Campaign Bookings',
    description: 'Available for high-fashion editorials, commercial campaigns, runway shows, and creative collaborations. Represented globally with experience spanning Vogue, GQ, Sports Illustrated, and international fashion weeks.',
    category: 'freelance',
    pricing: 'contact',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 2,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]
