import { ProfileWithLinks, Service } from '@/lib/types/database'

export const DENI_USERNAME = 'deni'

export const deniProfile: ProfileWithLinks = {
  id: 'demo-deni-001',
  username: 'deni',
  display_name: 'Deni Avdija',
  bio: 'NBA All-Star 🌟 Portland Trail Blazers #8 | 🇮🇱 Israeli-born, globally driven | Turning hustle into legacy on and off the court',
  avatar_url: '/demo/deni/avatar.png',
  theme: {
    primaryColor: '#E03A3E',
    backgroundColor: '#050505',
    fontFamily: 'Plus Jakarta Sans',
    buttonStyle: 'glass',
  },
  is_premium: true,
  custom_domain: null,
  onboarding_completed_at: '2024-01-01T00:00:00Z',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
  links: [
    {
      id: 'deni-link-1',
      profile_id: 'demo-deni-001',
      title: '🌟 2026 NBA All-Star — First Career Selection',
      url: 'https://www.nba.com/blazers/news/deni-avdija-selected-as-2026-all-star',
      icon: '🌟',
      position: 0,
      is_active: true,
      click_count: 48200,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'deni-link-2',
      profile_id: 'demo-deni-001',
      title: '🏀 Season Stats — 25.5 PPG / 7.2 RPG / 6.7 APG',
      url: 'https://www.espn.com/nba/player/_/id/4683021/deni-avdija',
      icon: '🏀',
      position: 1,
      is_active: true,
      click_count: 35800,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'deni-link-3',
      profile_id: 'demo-deni-001',
      title: '🇮🇱 "Israel\'s Greatest Player Ever" — NBA Feature',
      url: 'https://www.nba.com/news/the-athletic-deni-avdijas-unexpected-rise-to-nbas-new-breakout-star-and-israels-greatest-player-ever',
      icon: '🇮🇱',
      position: 2,
      is_active: true,
      click_count: 27500,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'deni-link-4',
      profile_id: 'demo-deni-001',
      title: '🔥 Season Highlights & Best Plays',
      url: 'https://www.youtube.com/results?search_query=deni+avdija+highlights+2026',
      icon: '🔥',
      position: 3,
      is_active: true,
      click_count: 19400,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'deni-link-5',
      profile_id: 'demo-deni-001',
      title: '🛒 Official Trail Blazers Merch — #8 Jersey',
      url: 'https://store.nba.com/portland-trail-blazers/deni-avdija/t-47031914+a-9029009816+z-98-2017933326',
      icon: '🛒',
      position: 4,
      is_active: true,
      click_count: 14700,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'deni-link-6',
      profile_id: 'demo-deni-001',
      title: '🏆 Portland Trail Blazers — Official Team',
      url: 'https://www.nba.com/blazers',
      icon: '🏆',
      position: 5,
      is_active: true,
      click_count: 11200,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  social_embeds: [
    {
      id: 'deni-social-1',
      profile_id: 'demo-deni-001',
      platform: 'instagram',
      embed_url: 'https://www.instagram.com/deniavdia8/',
      position: 0,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'deni-social-2',
      profile_id: 'demo-deni-001',
      platform: 'twitter',
      embed_url: 'https://x.com/deni_avdija',
      position: 1,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'deni-social-3',
      profile_id: 'demo-deni-001',
      platform: 'youtube',
      embed_url: 'https://www.youtube.com/results?search_query=deni+avdija',
      position: 2,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'deni-social-4',
      profile_id: 'demo-deni-001',
      platform: 'tiktok',
      embed_url: 'https://www.tiktok.com/@deniavdija',
      position: 3,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
  ],
}

export const deniServices: Service[] = [
  {
    id: 'deni-service-1',
    profile_id: 'demo-deni-001',
    title: 'Brand Partnerships & Endorsements',
    description: 'Collaborate with a 2026 NBA All-Star and Israel\'s most recognized athlete globally. Reach millions across the US, Israel, and Europe through authentic brand storytelling.',
    category: 'consulting',
    pricing: 'custom',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 0,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'deni-service-2',
    profile_id: 'demo-deni-001',
    title: 'Deni\'s Court — Youth Basketball Camp',
    description: 'Elite basketball training camp for youth players ages 10-18. Skill development, mentality coaching, and the work ethic that took me from Herzliya to the NBA All-Star Game. Summer 2026 in Tel Aviv & Portland.',
    category: 'event',
    pricing: 'fixed',
    price_amount: 450,
    price_currency: 'USD',
    action_type: 'book_meeting',
    action_config: {},
    position: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'deni-service-3',
    profile_id: 'demo-deni-001',
    title: 'Speaking & Appearances',
    description: 'Keynote speaking on perseverance, cross-cultural leadership, and the journey from Israeli youth basketball to the NBA. Available for corporate events, charity galas, and sports conferences.',
    category: 'event',
    pricing: 'contact',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 2,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]
