import { ProfileWithLinks, Service } from '@/lib/types/database'

export const YEHUDA_USERNAME = 'yehuda'

export const yehudaProfile: ProfileWithLinks = {
  id: 'demo-yehuda-001',
  username: 'yehuda',
  display_name: 'Yehuda Devir',
  bio: '🎨 "One of Those Days" Comic Creator | 🇮🇱 Israeli Artist | 10M+ Followers | Illustrating life with Maya & our kids',
  avatar_url: '/demo/yehuda/avatar.jpg',
  theme: {
    primaryColor: '#3B82F6',
    backgroundColor: '#050505',
    fontFamily: 'Plus Jakarta Sans',
    buttonStyle: 'glass',
  },
  is_premium: true,
  custom_domain: null,
  onboarding_completed_at: '2024-01-01T00:00:00Z',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
  links: [
    {
      id: 'yehuda-link-1',
      profile_id: 'demo-yehuda-001',
      title: '📖 "One of Those Days" Book — Amazon Bestseller',
      url: 'https://www.amazon.com/One-Those-Days-Yehuda-Devir/dp/0593231430',
      icon: '📖',
      position: 0,
      is_active: true,
      click_count: 87400,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'yehuda-link-2',
      profile_id: 'demo-yehuda-001',
      title: '🎨 Latest Comics — Instagram Gallery',
      url: 'https://www.instagram.com/jude_devir/',
      icon: '🎨',
      position: 1,
      is_active: true,
      click_count: 62300,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'yehuda-link-3',
      profile_id: 'demo-yehuda-001',
      title: '🛒 Official Merch Store — Prints, Stickers & More',
      url: 'https://www.yehudadevir.com/shop',
      icon: '🛒',
      position: 2,
      is_active: true,
      click_count: 34800,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'yehuda-link-4',
      profile_id: 'demo-yehuda-001',
      title: '🎬 YouTube — Animated Comics & Behind the Scenes',
      url: 'https://www.youtube.com/@yloyk',
      icon: '🎬',
      position: 3,
      is_active: true,
      click_count: 28500,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'yehuda-link-5',
      profile_id: 'demo-yehuda-001',
      title: '🖼️ ArtStation Portfolio — Full Illustration Gallery',
      url: 'https://yehudadevir.artstation.com/',
      icon: '🖼️',
      position: 4,
      is_active: true,
      click_count: 19200,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'yehuda-link-6',
      profile_id: 'demo-yehuda-001',
      title: '🌐 Official Website — yehudadevir.com',
      url: 'https://www.yehudadevir.com/',
      icon: '🌐',
      position: 5,
      is_active: true,
      click_count: 15600,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  social_embeds: [
    {
      id: 'yehuda-social-1',
      profile_id: 'demo-yehuda-001',
      platform: 'instagram',
      embed_url: 'https://www.instagram.com/jude_devir/',
      position: 0,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'yehuda-social-2',
      profile_id: 'demo-yehuda-001',
      platform: 'youtube',
      embed_url: 'https://www.youtube.com/@yloyk',
      position: 1,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'yehuda-social-3',
      profile_id: 'demo-yehuda-001',
      platform: 'tiktok',
      embed_url: 'https://www.tiktok.com/@yehuda_devir',
      position: 2,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'yehuda-social-4',
      profile_id: 'demo-yehuda-001',
      platform: 'twitter',
      embed_url: 'https://x.com/yabordeaux',
      position: 3,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
  ],
}

export const yehudaServices: Service[] = [
  {
    id: 'yehuda-service-1',
    profile_id: 'demo-yehuda-001',
    title: 'Commission Art — Custom Couple & Family Illustration',
    description: 'Get a custom "One of Those Days"-style illustration of you and your loved ones. Perfect for anniversaries, weddings, proposals, and family milestones. Hand-drawn by Yehuda in his signature comic style with vibrant colors and emotional storytelling.',
    category: 'freelance',
    pricing: 'fixed',
    price_amount: 500,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 0,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'yehuda-service-2',
    profile_id: 'demo-yehuda-001',
    title: 'Brand Collaborations — Illustrated Campaigns',
    description: 'Partner with one of the world\'s most-followed comic artists to create illustrated brand campaigns that resonate with millions. Previous collaborations include Disney, Netflix, Samsung, and El Al. Custom comic panels, animated shorts, and social media content.',
    category: 'consulting',
    pricing: 'custom',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'yehuda-service-3',
    profile_id: 'demo-yehuda-001',
    title: '"One of Those Days" Book — Illustrated Relationship Comics',
    description: 'The New York Times bestselling collection of Yehuda & Maya\'s hilarious and heartwarming relationship comics. 200+ pages of full-color illustrations capturing the funny, messy, and beautiful moments of life together. Available in hardcover and paperback.',
    category: 'product',
    pricing: 'fixed',
    price_amount: 25,
    price_currency: 'USD',
    action_type: 'external_link',
    action_config: { url: 'https://www.amazon.com/One-Those-Days-Yehuda-Devir/dp/0593231430' },
    position: 2,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]
