import { ProfileWithLinks, Service } from '@/lib/types/database'

export const GAL_USERNAME = 'gal'

export const galProfile: ProfileWithLinks = {
  id: 'demo-gal-001',
  username: 'gal',
  display_name: 'Gal Gadot',
  bio: '🎬 Wonder Woman | Actress & Producer | 🇮🇱 Israeli-born, Hollywood icon | Mother of 4 | Goodwill Ambassador',
  avatar_url: '/demo/gal/avatar.jpg',
  theme: {
    primaryColor: '#D4AF37',
    backgroundColor: '#050505',
    fontFamily: 'Plus Jakarta Sans',
    buttonStyle: 'glass',
  },
  is_premium: true,
  custom_domain: null,
  onboarding_completed_at: '2024-01-01T00:00:00Z',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
  links: [
    {
      id: 'gal-link-1',
      profile_id: 'demo-gal-001',
      title: '🦸‍♀️ Wonder Woman — The Complete Franchise',
      url: 'https://www.imdb.com/title/tt0451279/',
      icon: '🦸‍♀️',
      position: 0,
      is_active: true,
      click_count: 52300,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'gal-link-2',
      profile_id: 'demo-gal-001',
      title: '🎯 Red Notice — Netflix #1 Film',
      url: 'https://www.netflix.com/title/81093348',
      icon: '🎯',
      position: 1,
      is_active: true,
      click_count: 38700,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'gal-link-3',
      profile_id: 'demo-gal-001',
      title: '💎 Heart of Stone — Netflix Action Thriller',
      url: 'https://www.netflix.com/title/81497186',
      icon: '💎',
      position: 2,
      is_active: true,
      click_count: 29100,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'gal-link-4',
      profile_id: 'demo-gal-001',
      title: '👑 Snow White — The Evil Queen (2025)',
      url: 'https://www.imdb.com/title/tt5765804/',
      icon: '👑',
      position: 3,
      is_active: true,
      click_count: 21400,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'gal-link-5',
      profile_id: 'demo-gal-001',
      title: '🌍 UNICEF Goodwill Ambassador',
      url: 'https://www.unicef.org/goodwill-ambassadors',
      icon: '🌍',
      position: 4,
      is_active: true,
      click_count: 16800,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'gal-link-6',
      profile_id: 'demo-gal-001',
      title: '📸 Follow Me — 107M on Instagram',
      url: 'https://www.instagram.com/gal_gadot/',
      icon: '📸',
      position: 5,
      is_active: true,
      click_count: 44900,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  social_embeds: [
    {
      id: 'gal-social-1',
      profile_id: 'demo-gal-001',
      platform: 'instagram',
      embed_url: 'https://www.instagram.com/gal_gadot/',
      position: 0,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'gal-social-2',
      profile_id: 'demo-gal-001',
      platform: 'twitter',
      embed_url: 'https://x.com/GalGadot',
      position: 1,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'gal-social-3',
      profile_id: 'demo-gal-001',
      platform: 'youtube',
      embed_url: 'https://www.youtube.com/results?search_query=gal+gadot',
      position: 2,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'gal-social-4',
      profile_id: 'demo-gal-001',
      platform: 'tiktok',
      embed_url: 'https://www.tiktok.com/@gal_gadot',
      position: 3,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
  ],
}

export const galServices: Service[] = [
  {
    id: 'gal-service-1',
    profile_id: 'demo-gal-001',
    title: 'Brand Partnerships & Global Campaigns',
    description: 'Collaborate with one of the most recognized faces in the world. Gal has partnered with Tiffany & Co., Revlon, Reebok, Huawei, and SmartWater. Reach hundreds of millions across film, fashion, and social media.',
    category: 'consulting',
    pricing: 'custom',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 0,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'gal-service-2',
    profile_id: 'demo-gal-001',
    title: 'Speaking & Keynote Appearances',
    description: 'Keynote speaking on empowerment, breaking barriers in Hollywood, Israeli resilience, and balancing career with motherhood. Available for corporate summits, galas, women\'s leadership forums, and global events.',
    category: 'event',
    pricing: 'contact',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'gal-service-3',
    profile_id: 'demo-gal-001',
    title: 'Pilot Wave Motion Pictures — Production Company',
    description: 'Founded by Gal Gadot and Jaron Varsano, Pilot Wave develops premium film and television content. Currently producing projects with Skydance, Netflix, and Warner Bros. Open to co-production and development inquiries.',
    category: 'other',
    pricing: 'custom',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'external_link',
    action_config: { url: 'https://www.imdb.com/search/title/?companies=co0798tried' },
    position: 2,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]
