import { ProfileWithLinks, Service } from '@/lib/types/database'

export const NAS_USERNAME = 'nas'

export const nasProfile: ProfileWithLinks = {
  id: 'demo-nas-001',
  username: 'nas',
  display_name: 'Nas Daily',
  bio: '🌍 1-Minute Videos | 60M+ Followers | 🇮🇱🇵🇸 Israeli-Palestinian | Nas Academy Founder | That\'s 1 minute, see you tomorrow!',
  avatar_url: '/demo/nas/avatar.jpg',
  theme: {
    primaryColor: '#FF0000',
    backgroundColor: '#050505',
    fontFamily: 'Plus Jakarta Sans',
    buttonStyle: 'glass',
  },
  is_premium: true,
  custom_domain: null,
  onboarding_completed_at: '2024-01-01T00:00:00Z',
  created_at: '2024-01-01T00:00:00Z',
  updated_at: new Date().toISOString(),
  links: [
    {
      id: 'nas-link-1',
      profile_id: 'demo-nas-001',
      title: '🎬 YouTube — Nas Daily (1-Minute Videos)',
      url: 'https://www.youtube.com/@NasDaily',
      icon: '🎬',
      position: 0,
      is_active: true,
      click_count: 142300,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'nas-link-2',
      profile_id: 'demo-nas-001',
      title: '🎓 Nas Academy — Learn From The Best Creators',
      url: 'https://nasacademy.com',
      icon: '🎓',
      position: 1,
      is_active: true,
      click_count: 89400,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'nas-link-3',
      profile_id: 'demo-nas-001',
      title: '📱 Nas Daily App — Stories From Every Country',
      url: 'https://apps.apple.com/app/nas-daily/id1463024498',
      icon: '📱',
      position: 2,
      is_active: true,
      click_count: 56700,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'nas-link-4',
      profile_id: 'demo-nas-001',
      title: '🎤 TED Talk — Why Video Is The Future of Learning',
      url: 'https://www.ted.com/speakers/nuseir_yassin',
      icon: '🎤',
      position: 3,
      is_active: true,
      click_count: 38200,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'nas-link-5',
      profile_id: 'demo-nas-001',
      title: '📖 "Around the World in 60 Seconds" — My Book',
      url: 'https://www.amazon.com/Around-World-60-Seconds-Everything/dp/0062932683',
      icon: '📖',
      position: 4,
      is_active: true,
      click_count: 27800,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'nas-link-6',
      profile_id: 'demo-nas-001',
      title: '📘 Facebook — Nas Daily (45M+ Followers)',
      url: 'https://www.facebook.com/nasdaily',
      icon: '📘',
      position: 5,
      is_active: true,
      click_count: 21500,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-01-01T00:00:00Z',
    },
  ],
  social_embeds: [
    {
      id: 'nas-social-1',
      profile_id: 'demo-nas-001',
      platform: 'youtube',
      embed_url: 'https://www.youtube.com/@NasDaily',
      position: 0,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'nas-social-2',
      profile_id: 'demo-nas-001',
      platform: 'instagram',
      embed_url: 'https://www.instagram.com/nasdaily/',
      position: 1,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'nas-social-3',
      profile_id: 'demo-nas-001',
      platform: 'tiktok',
      embed_url: 'https://www.tiktok.com/@nasdaily',
      position: 2,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'nas-social-4',
      profile_id: 'demo-nas-001',
      platform: 'linkedin',
      embed_url: 'https://www.linkedin.com/in/nuseir-yassin/',
      position: 3,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
    {
      id: 'nas-social-5',
      profile_id: 'demo-nas-001',
      platform: 'twitter',
      embed_url: 'https://x.com/naikiw',
      position: 4,
      is_active: true,
      created_at: '2024-01-01T00:00:00Z',
    },
  ],
}

export const nasServices: Service[] = [
  {
    id: 'nas-service-1',
    profile_id: 'demo-nas-001',
    title: 'Nas Academy — Online Courses',
    description: 'Learn storytelling, video creation, and personal branding from world-class creators. Courses range from beginner to advanced, with community access and live sessions. Join 100K+ students globally.',
    category: 'education',
    pricing: 'fixed',
    price_amount: 97,
    price_currency: 'USD',
    action_type: 'external_link',
    action_config: { url: 'https://nasacademy.com' },
    position: 0,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'nas-service-2',
    profile_id: 'demo-nas-001',
    title: 'Brand Collaborations — Video Partnerships',
    description: 'Partner with Nas Daily for authentic branded content reaching 60M+ followers across Facebook, YouTube, Instagram, and TikTok. 1-minute story format with proven 10x engagement vs traditional ads. Past partners: Google, Airbnb, Wix, Saudi Tourism.',
    category: 'consulting',
    pricing: 'custom',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 1,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'nas-service-3',
    profile_id: 'demo-nas-001',
    title: 'Speaking Engagements — Keynotes & Events',
    description: 'Keynote talks on storytelling, building a global audience, bridging cultures, and the creator economy. Spoken at Harvard, Google, World Economic Forum, and 50+ countries. Available for corporate events, conferences, and universities.',
    category: 'event',
    pricing: 'contact',
    price_amount: null,
    price_currency: 'USD',
    action_type: 'contact_form',
    action_config: {},
    position: 2,
    is_active: true,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]
